package br.uff.graduatesapi.enums

enum class InstitutionType {
    PUBLIC_FEDERAL_UNIVERSITY,
    PUBLIC_FEDERAL_INSTITUTION,
    PUBLIC_STATE_INSTITUTION,
    PRIVATE_INSTITUTION,
    PUBLIC_ORGANIZATION,
    BUSINESS_OR_BRAZILIAN_INSTITUTION,
    BUSINESS_OR_INSTITUTIONS_ABROAD,
    OTHER
}