server:
  port: ${PORT}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
  mail:
    host: ${MAIL_SENDER_HOST}
    port: ${MAIL_SENDER_PORT}
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        transport:
          protocol: ${MAIL_SENDER_PROTOCOL}
        debug: ${MAIL_SENDER_DEBUG}
        smtp:
          auth: ${MAIL_SENDER_AUTH}
          starttls:
            enable: ${MAIL_SENDER_STARTTLS_ENABLE}
#mail-sender:
#  host: ${MAIL_SENDER_HOST}
#  port: ${MAIL_SENDER_PORT}
#  username: ${MAIL_SENDER_USERNAME}
#  password: ${MAIL_SENDER_PASSWORD}
#  protocol: ${MAIL_SENDER_PROTOCOL}
#  auth: ${MAIL_SENDER_AUTH}
#  starttls-enable: ${MAIL_SENDER_STARTTLS_ENABLE}
#  debug: ${MAIL_SENDER_DEBUG}

jwt:
  secret: ${JWT_SECRET}

token:
  expiration: ${TOKEN_EXPIRATION}

cors:
  originPatterns: ${CORS_ORIGINS}
