server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sistema_egressos
    username: postgres
    password: 123456123
  jpa:
    generate-ddl: true
    show-sql: true